// Generated by scripts/generate-runtime-config.mjs. Keep this file committed for clean checkouts.
export const generatedRuntimeConfig = {
  "repositoryMode": "mock",
  "apiBaseUrl": "",
  "companyWebsite": "",
  "playStoreUrl": "",
  "roadsideAssistancePhone": "",
  "buildEnvironment": "development"
} as const;
